### ISSUE TITLE
When run locally, document/references returns references that aren't in the initial root_path

### ISSUE THREAD

**Issue by uforic** [sourcegraph/go-langserver#11]
When debugging the go language server locally, I noticed that a references request pulled back refs that weren't in the root_path of the project.

Step 1: Initialize language server, notice the rootPath
`
language server initialized: [{"jsonrpc": "2.0", "id": 1, "result": {"capabilities": {"workspaceSymbolProvider": true, "textDocumentSync": 1, "definitionProvider": true, "hoverProvider": true, "referencesProvider": true}}}, {"request": {"params": {"capabilities": {}, "processId": 5506, "rootPath": "file:///Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph"}, "jsonrpc": "2.0", "id": 1, "method": "initialize"}}]
`

Step 2: Make a references call, was on net.Listener in server.go:
`
{'params': {'includeDeclaration': True, 'position': {'line': 43, 'character': 32}, 'textDocument': {'uri': 'file:///Users/mattfs/gopath/src/sourcegraph.com/sourcegraph/sourcegraph/pkg/gitserver/server.go'}}, 'jsonrpc': '2.0', 'id': 3, 'method': 'textDocument/references'}
`

Step 3: A sampling of results returned (over 130 results):
`
file:///Users/mattfs/gopath/src/github.com/chzyer/readline/remote.go
`
`
file:///Users/mattfs/gopath/src/github.com/rogpeppe/rog-go/loopback/net.go
`

Notice how none of these are vendored (how I know they aren't coming from Sourcegraph), and they all happen to be in my GOPATH.

Is it possible we are pulling all references to a given def that are in the GOPATH, not just the ones in the doc_root of the project we are in?

**Comment by keegancsmith** [comment]
This is actually the same behaviour as any other go plugin. (go guru searches the whole GOPATH). However, I agree that this is surprising behaviour for find _local_ references.

I am guessing we can do one (or more) of three things:
1. Limit results to `rootPath`.
2. Order results intelligently.
3. Wait until we references searches global as well (will still need 2).

(1) should be pretty easy to implement. (2) for just boosting results in rootPath should also be very easy.

cc @sqs

**Comment by sqs** [comment]
Iirc this is filed somewhere already or mentioned in code TODO. Agreed we should do (1) below now.

**Comment by uforic** [comment]
Cool - the main reason I'd like to do this is for performance, within an editor find all refs in Sourcegraph is taking ~10 seconds, and at that rate I think folks will choose to use "Find All."

I don't know if this adds too much code complexity, but I wonder if the ideal is to look inside of rootPath + dependencies. Trying to decide if this would be desirable behavior... For instance, it seems inconsistent that for those that vendor, they will see refs of deps, but for those who won't they won't.

**Comment by keegancsmith** [comment]
On sourcegraph.com it should just be rootPath + deps, unless I am mistaken. I don't think (1) should be that hard to implement.

**Comment by keegancsmith** [comment]
So we already do this filtering, it's just broken from Sublime due to an LSP extension we do called `RootImportPath`.  https://sourcegraph.com/github.com/sourcegraph/go-langserver@03af5b6677a58cc367e45483d89ea912fc7e5d3b/-/blob/langserver/lspx.go#L23-27
EG `github.com/kubernetes/kubernetes` has a `RootImportPath` of `k8s.io/kubernetes`.

Currently that is always empty from Sublime, since it doesn't do the calculation. On sourcegraph.com our buildserver calculates this value using a heuristic which tries to find package import paths, but otherwise falls back to the path. 

An empty `RootImportPath` is actually treated as a special value, meaning we are looking at the stdlib. This means workspace/ commands are probably broken if we started using them from Sublime.

@sqs you introduced the `RootImportPath`. Should we port the import path code? I assume not, since it makes assumptions on GOPATH layout. Instead we probably need a way to tell the LSP server to ignore the `RootImportPath` (maybe make stdlib not the empty string?)

**Comment by keegancsmith** [comment]
BTW doing the filtering won't actually make any of this faster, since we use `importgraph.Build` https://sourcegraph.com/github.com/sourcegraph/go-langserver@03af5b6677a58cc367e45483d89ea912fc7e5d3b/-/blob/langserver/references.go#L34

Creating a patched version of `importgraph.Build` is what we need to do to speed up this operation.

**Comment by keegancsmith** [comment]
I have a potentially terrible hack which will allow us to use `importgraph.Build`, adjust the `build.Context` such that we fail to read any file outside of the `rootPath` :O

**Comment by uforic** [comment]
Haha nice - seems like a reasonable approach :-) .

That will miss non-vendored projects though, right? Like if I'm depending on github.com/gorilla/mux , and it's not vendored, than it won't be in the rootPath. FWIW, I think this could be a reasonable approach. Another data point: it looks like VSCode grabs the entire GOPATH references, I noticed a find all refs on "Handler" in our project returns stuff from cockroachDB.

Re: importgraph.Build - why does that prevent us from making things faster? Does it by default scan the whole GOPATH?

What would you guys expect for find all refs? _just_ refs in the project you are in, refs in the project + deps (including Go STL), or refs in everything in GOPATH?

Choice 2, then 1, then 3 would be my preference list.

**Comment by keegancsmith** [comment]
`importgraph.Build` is used by `guru` and `go-langserver` to find all references. It looks at the whole GOPATH. This behaviour is surprising to others as well and someone filed an issue about it a while ago https://github.com/golang/go/issues/14747 and https://github.com/golang/go/issues/14748

What we can actually do is cache `importgraph.Build` so at least future calls to references is faster, but that likely will lead to us giving wrong results for long running langservers + people updating there GOPATH. However, that is an issue we can defer to fixing later since we likely have lots of issues along those lines (not invalidating caches since we don't need to on sourcegraph.com). As such I'll send out a PR about caching it, and we can discuss it on there.

> What would you guys expect for find all refs? just refs in the project you are in, refs in the project + deps (including Go STL), or refs in everything in GOPATH?

It totally depends on what I am querying. I think intelligently ordering results will get us what we want. I'll take a stab at using the lowest common ancestor to our query path. That mixed with the caching will get us the speed we want.
