### ISSUE TITLE
Release go-langserver on gopkg.in

### ISSUE THREAD

**Issue by beyang** [sourcegraph/go-langserver#154]
Version numbers should match the version of vscode-go that the go-langserver version should be used with. The binary should also report its version number. vscode-go will check the version number reported by the binary and update (via `go get gopkg.in/go-langserver.v$VERSION`) if necessary.

Given the need to update the version number, it may be helpful to write a small script that writes the version and tags the commit at the same time.

We'll need this sometime in the next month for the next release of vscode-go.

**Comment by keegancsmith** [comment]
Note: it will be something like `go get gopkg.in/go-langserver.v$VERSION/langserver/cmd/go-langserver` which is pretty ugly. We should just move the main.go into the top-level so we can just do `go get gopkg.in/go-langserver.v$VERSION`. We should also start vendoring our dependencies to make the build more reproducible.

**Comment by ramya-rao-a** [comment]
To begin with, can we have versions as tags on the commits, so that users can check what version they have and if they need to update?

Next step would be to have something like `go-langserver version` just like `go version` to output the version.

VS Code Go plugin can maintain the minimum version that it expects user to have and prompt appropriately.
