### ISSUE TITLE
Hover doesn't work for builtins

### ISSUE THREAD

**Issue by zmb3** [sourcegraph/go-langserver#174]
I'm not able to get any doc for builtins when using the language server in VS Code.

Before enabling language server, I could hover over a builtin and get doc:
![builtin](https://cloud.githubusercontent.com/assets/7527103/23754860/b987b6f2-049b-11e7-8945-b7e73ff3839d.png)

After enabling language server, nothing happens when I hover over a builtin (`make`, `append`, `len`, `cap`, etc.)

**Comment by keegancsmith** [comment]
Thanks for filing this issue. It is a known issue that we don't support operations like hover, j2d and references on builtins. However, we didn't have an issue filed so thanks for that! Some other info given this issue now exists:

* For hover we should definitely add support.
* For j2d on builtins the potential destination isn't that interesting, so less obvious that it is valuable to add.
* For references we explicitly do not support it, since the number of references would be very high and as such seem uninteresting. Happy to change my mind on that if someone can give a decent argument why they would use it.

**Comment by zmb3** [comment]
> For j2d on builtins the potential destination isn't that interesting, so less obvious that it is valuable to add.

I completely agree.  I don't support definition for builtins in [gogetdoc](https://github.com/zmb3/gogetdoc) (the tool that used to power the hover provider) either.

> For references we explicitly do not support it, since the number of references would be very high and as such seem uninteresting.

Sounds like the right choice to me.

**Comment by frou** [comment]
> For references we explicitly do not support it, since the number of references would be very high and as such seem uninteresting. Happy to change my mind on that if someone can give a decent argument why they would use it.

It doesn't seem far-fetched to want to find all uses of `panic` in a codebase. Or `close` when debugging channel behaviour. Or `make` when optimizing (adding capacities in addition to lengths at slice make sites).
