### ISSUE TITLE
Code completion.

### ISSUE THREAD

**Issue by hibooboo2** [sourcegraph/go-langserver#201]
Why is auto complete / code completion not supported? If it is why is it not shown in the graph on langserver.org ?

**Comment by beyang** [comment]
Hi James! It's not supported simply because we haven't gotten around to implementing it yet. The initial use case for this language server was in a read-only setting. It is high up on our list of wanted features and I think it would be a fairly straightforward feature to implement with standard Go tooling. We're not actively working on it at the moment, but would accept pull requests from the community.
