### ISSUE TITLE
[Question] How easy would it be to make a language server library from this code?

### ISSUE THREAD

**Issue by awilkins** [sourcegraph/go-langserver#205]
Specific use case : I find myself wanting a Terraform language server.

Terraform is written in Go. I feel like the best plan is to implement a language server that can consume all of Terraform's code to mine it for type information on the various resources.

Since this is a language server written in Go... is there a good enough break here between "implements a language server *in* Go" and "implements a language server *for* Go" to make it simple to write other language servers *in* Go?

**Comment by keegancsmith** [comment]
I actually considered writing a terraform LS a while ago for fun, but never found the time. So I agree with your idea. The `pkg/lsp` type definitions you will find useful. Otherwise there really isn't that much that you could share with the stuff in `langserver`, nor would you want to. You basically just want `pkg/lsp` and the `jsonrpc2` package. To implement your handler take a look at this entry point https://github.com/sourcegraph/go-langserver/blob/master/langserver/handler.go#L131 Note: Our handler code is kinda over-engineered because we use and compose parts of it in our private code.

**Comment by awilkins** [comment]
Thanks for the pointers!
