### ISSUE TITLE
Extreme High memory & CPU with GitHub Desktop on Windows 10

### ISSUE THREAD

**Issue by Ekalu** [sourcegraph/go-langserver#207]
Hello, I hope some one can help me out here. I am trying to use GitHub with Unreal Engine 4 and have been getting extremely bad issues while using GitHub. Apparently my Memory and CPU both will go as high as 99% to 100% on both when I launch either GitHub Desktop or SourceTree (which uses GitHub and not as bad with CPU usage as GitHub Desktop). I have noticed that when I open the task manager I can see multiple GitHub items in the list and can watch the CPU and Memory % both begin to rise as soon as I start GitHub. It will slowly rise beginning from 3% and keep rising till it maxes out in about 1 min time or less. Any idea what is going on or how to solve this? I had to close out every Github Option in Task manage just so I can come here to ask for some help with it. Here are a few screen shots to show what I mean:

![github](https://user-images.githubusercontent.com/13180964/31692074-8d3cda1e-b355-11e7-894e-66f8076d81e9.jpg)
![github2](https://user-images.githubusercontent.com/13180964/31692078-901dead4-b355-11e7-88a3-b3a6e200ab86.jpg)

Thanks for your time and help.
P.S. My system contains an I7 2600k 4 core CPU and Github will max all 4 cores. System memory is 32gig 1600 MHz

**Comment by Ekalu** [comment]
Update: I have just restarted my system and decided to try some thing a bit different and discovered a possible issue that may be the cause.I had tested it this way:

1. Opened Task Manager
2. started GitHub Desktop
3. Tried to import my Unreal Engine Project to push to GitHub online
4. When option to start Git LFS I pressed the ok button to start it. From here I noticed in the task manager the CPU and Memory both started to raise and gone up to max once again. I believe it is very possible that the Git-LFS is the cause to the leaks that may been giving so many people trouble. Only when I started the Git-LFS is when I had noticed the issue. Any one have an idea how to fix this or is there a patch for this issue yet?

**Comment by slimsag** [comment]
Hi @Ekalu it seems like your issue is specific to [GitHub Desktop](https://desktop.github.com/) and is not related to the Sourcegraph Go Language Server at all?

If so, you'll need to contact GitHub directly as there is nothing we can do to help you (we're not associated with GitHub). :) You can probably reach them via email or twitter.

You can also file it as a Git LFS issue here: https://github.com/git-lfs/git-lfs

I'll close this issue since it isn't related to this project, but I hope my above response gives you some idea of where to go for help on this :)
