### ISSUE TITLE
Why TextDocumentSyncKind.Incremental is implemented but not used?

### ISSUE THREAD

**Issue by Contextualist** [sourcegraph/go-langserver#210]
I notice that the handler is capable to process incremental changes in `textDocument/didChange` event.
https://github.com/sourcegraph/go-langserver/blob/885ad3639de0e1e6c230db5395ea0f682534b458/langserver/fs.go#L154-L159
However, in the initial parameters, the sever declares its capability as `TextDocumentSyncKind.Full`
https://github.com/sourcegraph/go-langserver/blob/885ad3639de0e1e6c230db5395ea0f682534b458/langserver/handler.go#L205-L210
What's the reason for prefering Full than Incremental?

**Comment by keegancsmith** [comment]
The server doesn't process notifications necessarily in the order they are received, since we spin up a goroutine for each received jsonrpc2 request/notif. Which means we may apply the incremental patches in the wrong order depending on the whims of the go runtime. Once that is fixed we can start using the incremental patches again.

**Comment by Contextualist** [comment]
I see, but now the server uses `jsonrpc2.HandlerWithError`(a sync handler) instead of `jsonrpc2.AsyncHandler`, and `lspHandler` wraps `LangHandler` so that the requests that mutate the typecheckers (e.g. `textDocument/didChange`) are blocking. Am I correct to assume that all changes to the document are processed serially?

**Comment by keegancsmith** [comment]
@Contextualist you are right, I forgot I "fixed" that :) We should be fine with using incremental.
