### ISSUE TITLE
Feature request: Completion provider

### ISSUE THREAD

**Issue by uforic** [sourcegraph/go-langserver#27]
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#completion-request

**Comment by keegancsmith** [comment]
@uforic what is the priority on this? Is this something covered by some of the new work by @alexsaveliev?

**Comment by uforic** [comment]
Let's table this for now, too much other fun stuff to work on - closing.

**Comment by acornejo** [comment]
From what I can tell it seems go-langserver was built primarily to power sourcegraph codesearch backend, and in that scenario autocompletion doesn't really make sense since codesearch is not for editting code just navigating it.

I was looking for a go langserver to use for editing and I came across this, but from an editor's perspective autocomplete is perhaps the MOST important feature in LSP.

I am trying to evaluate whether it is easier to add LSP functionality to nsf/gocode (which is already an autocompletion deamon, just using a non standard protocol), or to add autocompletion to go-langserver. 

I see that several autocompletion requests have been filed in this repository (like this one, which was filed over a year ago) and not much progress has been made, so I assume its a non trivial amount of work.

Similarly I see nsf/gocode/issues/386 which makes it sound like adding LSP support to gocode is not as straigthforward as one would think.

Thoughts?

**Comment by keegancsmith** [comment]
For alternative projects:
* There is https://github.com/theia-ide/go-language-server which is essentially taking vscode-go extension and making it speak LSP instead of `vscode.ts`
* There is another experimental go language server in the works at https://github.com/dominikh/go-tools/issues/136 I am confident it will be high quality when it is ready, and possibly supersede this project.

As for adding support to this implementation, it probably isn't that hard. You are right that this was written with the read-only use case in mind, and we haven't made great progress on the usual editor use case. As for how to add it, I believe you take the `godef` part of the code, and once it has a definition you "guess" at what those completions are. I think godef is pretty robust at code that doesn't compile, but to be honest I haven't tested it much due to the sourcegraph use case.

Good luck and please let me know which direction you end up attempting.

**Comment by Contextualist** [comment]
I have tried adding the completion feature to go-langserver by vendoring gocode and adapting its interface to LSP (just exposing a single function & translating request/response, not a great amount of work). It actually works, but I am not sure if it's an optimal way or there are caveats unspotted. I can open a PR if it is really wanted.

**Comment by keegancsmith** [comment]
Yeah we have had issues in the past with memory use so I get the feeling this might not be optimal use of memory. However, I am keen to add it with a command line flag to enable. Try it out for a bit then if it works well we just have it enabled by default.

So @Contextualist the PR sounds good to me :)

**Comment by acornejo** [comment]
Thanks for the feedback @keegancsmith. FWIW my understanding is that vscode-go relied on gocode for completion, so if https://github.com/theia-ide/go-language-server  works it is the equivalent of wrapping gocode with LSP protocol.

Regarding the idea of extending go-to-definition to get autocompletion, unfortunately I think its a bit more than that.

What you described would work only for:

type.<tab> complete for members of type

However users will also expect completion for:

packagename.<tab> complete for all interfaces and functions exported by package
identifier.<tab> first you have to map what is the type of identifier

These use cases are already handled by gocode.
