### ISSUE TITLE
consider a more structured code layout

### ISSUE THREAD

**Issue by slimsag** [sourcegraph/go-langserver#85]
From my very harsh/critical perspective, `go-langserver` is rapidly becoming a giant glob of code living in a single directory. This is bad because our code documentation can rapidly become out of date or interconnected pieces can be altered affecting other things unintentionally.

This is less of a "I have a concrete plan" and more of a "let's chat about how we can improve this" issue. Ideally we have a top-down polytree structure without any cyclic dependencies etc.

One good example is how `langserver/internal/refs` is totally separate from the main package. Granted, more of the external references code in `workspace_refs.go` can and should be moved away from the main `langserver` package -- but it's a good reference idea here.

Take this as a plea from me to find and place code that is sufficiently independent and factor it out into smaller separate `internal` subpackages @keegancsmith :) (I'll be trying to do this actively, too, obviously)

**Comment by keegancsmith** [comment]
I agree, its organic growth has led to code that could be better structured, so we should do some improvements. I'm not sure if subpackages (excluding for larger bits of code such as refs or symbols) would actually make life easier though. I think the bigger win would be better thought put into how all the shared state is accessed/separated out. Right now we have stuff split out over files in a haphazard way, but it is all essentially doing things to `LangHandler`. So that seems like a good win rather than just moving code around.

BTW I don't see our code layout as a bad thing. I'm glad we got to this point of confusing code! Because now I think it is more obvious how we can improve the codebase, than if we designed it upfront when all we supported was hover, ref and j2d. But yes, prioritizing some refactoring/cleanup work is super important, especially if we want more outside contributors to not just run away when they open up this codebase.

**Comment by keegancsmith** [comment]
I'm going to try ship a few small changes this week which should start shaping us to a codebase that makes more sense. The mini-goal I set this week is making https://godoc.org/github.com/sourcegraph/go-langserver/langserver look reasonable. The first PR is here https://github.com/sourcegraph/go-langserver/pull/87
